var lists = [{
    ProductID : 1,
    referencenum : 8305,
    isfnum : "",
    importer : "Importer test Company",
    etl : "4/15/09",
    eta : "5/1/09",
    carrier : "HDMU",
    masterbill : "MAEU",
    housebill : "123455",
    transactiontype : "CT",
    createdtime : "3/19/09 4:37 PM",
    isfcompleted : "Yes",
    billonfile : "No",
    customstatus : "Rejected",
},
{
    ProductID : 2,
    referencenum : 8305,
    isfnum : "",
    importer : "Importer test Company",
    etl : "4/15/09",
    eta : "5/1/09",
    carrier : "HDMU",
    masterbill : "MAEU",
    housebill : "123455",
    transactiontype : "CT",
    createdtime : "3/19/09 4:37 PM",
    isfcompleted : "Yes",
    billonfile : "No",
    customstatus : "Rejected",
},
{
    ProductID : 3,
    referencenum : 8305,
    isfnum : "",
    importer : "Importer test Company",
    etl : "4/15/09",
    eta : "5/1/09",
    carrier : "HDMU",
    masterbill : "MAEU",
    housebill : "123455",
    transactiontype : "CT",
    createdtime : "3/19/09 4:37 PM",
    isfcompleted : "Yes",
    billonfile : "No",
    customstatus : "Rejected",
},
{
    ProductID : 4,
    referencenum : 8305,
    isfnum : "",
    importer : "Importer test Company",
    etl : "4/15/09",
    eta : "5/1/09",
    carrier : "HDMU",
    masterbill : "MAEU",
    housebill : "123455",
    transactiontype : "CT",
    createdtime : "3/19/09 4:37 PM",
    isfcompleted : "Yes",
    billonfile : "No",
    customstatus : "Rejected",
},
{
    ProductID : 5,
    referencenum : 8305,
    isfnum : "",
    importer : "Importer test Company",
    etl : "4/15/09",
    eta : "5/1/09",
    carrier : "HDMU",
    masterbill : "MAEU",
    housebill : "123455",
    transactiontype : "CT",
    createdtime : "3/19/09 4:37 PM",
    isfcompleted : "Yes",
    billonfile : "No",
    customstatus : "Rejected",
},
{
    ProductID : 6,
    referencenum : 8305,
    isfnum : "",
    importer : "Importer test Company",
    etl : "4/15/09",
    eta : "5/1/09",
    carrier : "HDMU",
    masterbill : "MAEU",
    housebill : "123455",
    transactiontype : "CT",
    createdtime : "3/19/09 4:37 PM",
    isfcompleted : "Yes",
    billonfile : "No",
    customstatus : "Rejected",
},
{
    ProductID : 7,
    referencenum : 8305,
    isfnum : "",
    importer : "Importer test Company",
    etl : "4/15/09",
    eta : "5/1/09",
    carrier : "HDMU",
    masterbill : "MAEU",
    housebill : "123455",
    transactiontype : "CT",
    createdtime : "3/19/09 4:37 PM",
    isfcompleted : "Yes",
    billonfile : "No",
    customstatus : "Rejected",
},
{
    ProductID : 8,
    referencenum : 8305,
    isfnum : "",
    importer : "Importer test Company",
    etl : "4/15/09",
    eta : "5/1/09",
    carrier : "HDMU",
    masterbill : "MAEU",
    housebill : "123455",
    transactiontype : "CT",
    createdtime : "3/19/09 4:37 PM",
    isfcompleted : "Yes",
    billonfile : "No",
    customstatus : "Rejected",
},
{
    ProductID : 9,
    referencenum : 8305,
    isfnum : "",
    importer : "Importer test Company",
    etl : "4/15/09",
    eta : "5/1/09",
    carrier : "HDMU",
    masterbill : "MAEU",
    housebill : "123455",
    transactiontype : "CT",
    createdtime : "3/19/09 4:37 PM",
    isfcompleted : "Yes",
    billonfile : "No",
    customstatus : "Rejected",
},
{
    ProductID : 10,
    referencenum : 8305,
    isfnum : "",
    importer : "Importer test Company",
    etl : "4/15/09",
    eta : "5/1/09",
    carrier : "HDMU",
    masterbill : "MAEU",
    housebill : "123455",
    transactiontype : "CT",
    createdtime : "3/19/09 4:37 PM",
    isfcompleted : "Yes",
    billonfile : "No",
    customstatus : "Rejected",
},
{
    ProductID : 11,
    referencenum : 8305,
    isfnum : "",
    importer : "Importer test Company",
    etl : "4/15/09",
    eta : "5/1/09",
    carrier : "HDMU",
    masterbill : "MAEU",
    housebill : "123455",
    transactiontype : "CT",
    createdtime : "3/19/09 4:37 PM",
    isfcompleted : "Yes",
    billonfile : "No",
    customstatus : "Rejected",
}
]